book_titles = {
"Flatland",
"The Hitchhiker's Guide to the Galaxy",
"The Restaurant at the End of the Universe",
"Live, the Universe and Everything",
"So Long, and Thanks for all the Fish",
"Mostly Harmless",
"And Another Thing...",
"Simon vs. The Homo Sapiens Agenda",
"Little Women",
"The House of the Spirits",
"Foundation",
"I, Robot",
"The Martian Chronicles",
"March",
"The Sword of Shannara",
"Antrax",
"Tanequil",
"Morgawr",
"Jarka Ruus",
"Straken",
"The Princess of Mars",
"The Warlord of Mars",
"Thuvia, Maid of Mars",
"The Chessmen of Mars",
"The Master Mind of Mars",
"Ender's Game",
"The Education of Little Tree",
"The Perk of Being a Wallflower",
"Arrival",
"Utopia Cild",
"Al Capone Does My Shirts",
"Rainbow Six",
"Clockwork Angel",
"City of Heavenly Fire",
"Childhood's End",
"Artemis Fowl",
"The Artic Incident",
"The Hunger Games",
"The Schorch Trials",
"A Tale of Two Cities",
"Do Androids Dream of Electric Sheep?",
"Axiom's End",
"I Have no Mouth and I Must Scream",
"How to be a Time Lord Official Guide",
"The Prisoner of Cell 25",
"Tsotsi",
"Neuromancer",
"The Fault in our Stars",
"Paper Towns",
"Lord of the Flies",
"The Left Hand of Darkness",
"Dune",
"Stranger in a Strange Land",
"The Cry of the Icemark",
"Blade of Fire",
"Last Battle of the Icemark",
"Point Blank",
"Eagle Strike",
"Raven's Gate",
"Stormbreaker",
"A Thousand Splendid Suns",
"One Flew Over the Cuckoo's Nest",
"The Gunslinger",
"The Dark Tower (The Dark Tower, #7)",
"The Poisonwood Bible",
"The Girl with the Dragon Tattoo",
"Prodigal Son",
"City of Night",
"Dead and Alive",
"Magic's Pawn",
"Perelandra (The Space Trilogy, #2)",
"That Hideous Strength",
"The Four Loves",
"Reflections on the Psalms",
"The Screwtape Letters",
"Mere Christianity",
"The Great Divorce",
"The Problem of Pain",
"Miracles by CS Lewis",
"A Grief Observed",
"Fire From Heaven",
"The Three Body Problem",
"The Dark Forest",
"Death's End",
"The Locus Awards",
"The Fall of Five",
"The Power of Six",
"The Complete Cthulhu Mythos Tales",
"The Giver",
"Legend",
"The Rivers of Zadaa",
"As Meat Loves Salt",
"The Song of Achilles",
"Circe",
"A Game of Thrones",
"China Mountain Zhang",
"Seeker",
"Belover",
"what if?",
"The False Prince",
"Ringworld",
"The Mote in God's Eye",
"Nineteen Eighty-four",
"Eragon",
"Eldest",
"Inheritance",
"The Westing Game",
"Revelation Space",
"Divergent",
"Insurgent",
"The House of Hades",
"The Casual Vacancy",
"Harry Potter and the Sorcerer's Stone",
"Harry Potter and the Chamber of Secrets",
"Harry Potter and the Prisoner of Azkaban",
"Harry Potter and the Goblet of Fire",
"Harry Potter and the Order of the Phoenix",
"Harry Potter and the Half-Blood Prince",
"Sacrati",
"Homeland Drizzt",
"Exile Drizzt",
"Sojourn Drizzt",
"The Crystal Shard Drizzt",
"Streams of Silver Drizzt",
"The Halfling's Gem Drizzt",
"The Legacy Drizzt",
"Starless Night Drizzt",
"Siege of Darkness Drizzt",
"Passage to Dawn Drizzt",
"Silent Blade Drizzt",
"The Spine of the World Drizzt",
"Sea of Swords Drizzt",
"Servant of the Shard",
"Promise of the Witch-King",
"Road of the Patriarch",
"The Thousand Orcs",
"The Lone Drow",
"The Two Swords",
"Steelheard",
"The Last Wish",
"Sword of Destiny",
"Macbeth",
"Frankenstein",
"The Jungle",
"The Barrow",
"The Winter of Our Discontent",
"Heroes of the Valley",
"The Joy Luck Club",
"The Kitchen God's Wife",
"The Hobbit",
"The Fellowship of the Ring",
"The Two Towers",
"The Return of the King",
"The Silmarillion",
"Artemis",
"The Martian",
"The Dragons of Autum Twilight",
"Dragons of Winter Night",
"Dragons of Spring Dawning",
"The Picture of Dorian Gray",
"Spin Wilson",
"The Sorcerer of the Wildeeps",
"The Road to Science Fiction #3",
"Player's Handbook",
"Dungeon Master's Guide",
"Volo's Guide to Monsters",
"Mordenkainen's Tome of Foes",
"Xanathar's Guide to Everything",
"Waterdeep Dungeon of the Mad Mage",
"Icewind Dale Rime of the Frostmaiden",
"Tales From the Yawning Portal",
"Waterdeep Dragon Heist",
"Out of the Abyss",
"Storm King's Thunder",
"Baldur's Gate Descent into Avernus",
"Princes of the Apocalypse",
"Curse of Strahd",
"The Rise of Tiamat",
"Hoard of the Dragon Queen",
"Tomb of Annihilation",
"Ghosts of Saltmarsh",
"Mythic Odyssys of Theros",
"Eberron Rising from the Last War",
"Tal'Dorei Campaign Setting",
"Explorer's Guide to Wildmount",
"GuildMasters' Guide to Ravnica",
"Sword Coast Adventurer's Guide",
"Encyclopedia Magica Volume 1",
"Encyclopedia Magica Volume 2",
"Encyclopedia Magica Volume 3",
"The Chronicles of Exandria",
"The Silver Chair",
"The Voyage of the Dawn Treader",
"The Missing Chums",
"The Tower Treasure",
"Prince Caspian",
"The Last Battle",
"The Horse and His Boy",
"The Pilgrim's Progress"
}
